#!/bin/sh
BROWSER=chrome
docker rm -f container-ruby-${BROWSER}
docker rm -f selenium-hub-${BROWSER}
docker pull selenium/standalone-${BROWSER}
docker run -d --shm-size="256m" --name selenium-hub-${BROWSER} selenium/standalone-${BROWSER}
docker build -t ruby/container-ruby-${BROWSER} .
docker run -v "$(pwd)":/opt/cucumber/ -e BROWSER=${BROWSER} --name container-ruby-${BROWSER} --link selenium-hub-${BROWSER}:selenium-hub-${BROWSER} ruby/container-ruby-${BROWSER} $@
docker rm -f container-ruby-${BROWSER}
docker rm -f selenium-hub-${BROWSER}
